name: Machine Learning Client CI

on:
  push:
    paths:
      - 'machine-learning-client/**'
  pull_request:
    paths:
      - 'machine-learning-client/**'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Install Python Dependencies
      run: |
        cd machine-learning-client
        pip install pipenv
        pipenv install --system --deploy

    - name: Run Unit Tests
      run: |
        cd machine-learning-client
        pytest --maxfail=5 --disable-warnings

    - name: Lint Code
      run: |
        cd machine-learning-client
        pylint app.py test_app.py generate_audio.py
