name: ML Client CI / CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install portaudio
      run: |
        sudo apt-get update
        sudo apt-get install -y portaudio19-dev

    - name: Install Dependencies
      run: |
          python -m venv venv
          venv/bin/pip install --upgrade pip
          venv/bin/pip install -r machine-learning-client/requirements.txt
          venv/bin/pip install pytest pytest-cov pylint

    - name: List Installed Packages
      run: |
          venv/bin/pip list

    - name: Run linting
      run: |
          venv/bin/python -m pylint machine-learning-client

    - name: Run tests with coverage
      run: |
          venv/bin/python -m pytest machine-learning-client/test_main.py --cov=machine-learning-client/main --cov-report=html
