name: Test Setup
on: [push, pull_request]

jobs:
  setup-test-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          cd machine-learning-client
          python -m pip install --upgrade pip
          pip install -r requirements.txt 