name: Web-App CI

on:
  push:
    paths:
      - 'web-app/**'
  pull_request:
    paths:
      - 'web-app/**'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python Dependencies
      run: |
        cd web-app
        pip install pipenv
        pipenv install --system --deploy

    - name: Run Unit Tests
      run: |
        cd web-app
        pytest --maxfail=5 --disable-warnings

    - name: Lint Code
      run: |
        cd web-app
        pylint app.py test_app.py
